/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";
import * as THREE from "three";

export function Rophnan1(props) {
  const stoneMaterial = new THREE.MeshStandardMaterial({ color: 0xbbb7ac });
  const { nodes, materials } = useGLTF("models/rophnan-scene.glb");

  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <PerspectiveCamera
          name="Camera"
          makeDefault={false}
          far={1000}
          near={0.1}
          fov={43.78}
          position={[2.21, 1.9, 15.78]}
          rotation={[0.05, 0.05, 0]}
          scale={[1, 1, 1.19]}
        />
        <spotLight
          name="Area"
          intensity={375.71}
          angle={Math.PI / 8}
          penumbra={0.15}
          color={"orange"}
          decay={2}
          position={[2.06, 6.87, 11.73]}
          rotation={[-1.26, -0.04, 0.98]}
          scale={[1, 1, 0.61]}
        >
          <group position={[0, 0, -1]} />
        </spotLight>
        <group
          name="Area001"
          position={[1.88, 35.16, 8.48]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1, 1, 1.19]}
        />
        <mesh
          name="spear_window"
          castShadow
          receiveShadow
          geometry={nodes.spear_window.geometry}
          material={materials.Yellow}
          position={[-9.38, 2.27, -12.92]}
          rotation={[0, 0.64, 0]}
          scale={[1, 1.19, 1]}
        />
        <mesh
          name="spear_window001"
          castShadow
          receiveShadow
          geometry={nodes.spear_window001.geometry}
          material={materials.Yellow}
          position={[10.47, 2.27, -12.53]}
          rotation={[0, -0.73, 0]}
          scale={[1, 1.19, 1]}
        />
        <mesh
          name="spear_window002"
          castShadow
          receiveShadow
          geometry={nodes.spear_window002.geometry}
          material={materials.Yellow}
          position={[14.94, 2.15, -6.39]}
          rotation={[0.02, -1.18, 0]}
          scale={[1, 1.19, 1]}
        />
        <mesh
          name="spear_window003"
          castShadow
          receiveShadow
          geometry={nodes.spear_window003.geometry}
          material={materials.Yellow}
          position={[-13.88, 2.27, -8.06]}
          rotation={[0, 1.07, 0]}
          scale={[1, 1.19, 1]}
        />
        <mesh
          name="pillar_1"
          castShadow
          receiveShadow
          geometry={nodes.pillar_1.geometry}
          material={materials.Yellow}
          position={[15.58, 3.35, 3.82]}
          scale={[0.64, 0.78, 0.64]}
        />
        <mesh
          name="pillar_2"
          castShadow
          receiveShadow
          geometry={nodes.pillar_2.geometry}
          material={materials.Yellow}
          position={[15.7, 3.35, -3.19]}
          scale={[0.64, 0.78, 0.64]}
        />
        <mesh
          name="pillar_3"
          castShadow
          receiveShadow
          geometry={nodes.pillar_3.geometry}
          material={materials.Yellow}
          position={[12.86, 3.35, -9.59]}
          scale={[0.64, 0.78, 0.64]}
        />
        <mesh
          name="pillar_4"
          castShadow
          receiveShadow
          geometry={nodes.pillar_4.geometry}
          material={materials.Yellow}
          position={[7.54, 3.35, -14.15]}
          scale={[0.64, 0.78, 0.64]}
        />
        <mesh
          name="pillar_5"
          castShadow
          receiveShadow
          geometry={nodes.pillar_5.geometry}
          material={materials.Yellow}
          position={[-6.12, 3.35, -14.84]}
          scale={[0.64, 0.78, 0.64]}
        />
        <mesh
          name="pillar_6"
          castShadow
          receiveShadow
          geometry={nodes.pillar_6.geometry}
          material={materials.Yellow}
          position={[-11.84, 3.35, -10.8]}
          scale={[0.64, 0.78, 0.64]}
        />
        <mesh
          name="pillar_7"
          castShadow
          receiveShadow
          geometry={nodes.pillar_7.geometry}
          material={materials.Yellow}
          position={[-15.33, 3.35, -4.72]}
          scale={[0.64, 0.78, 0.64]}
        />
        <mesh
          name="pillar_8"
          castShadow
          receiveShadow
          geometry={nodes.pillar_8.geometry}
          material={materials.Yellow}
          position={[-15.89, 3.35, 2.26]}
          scale={[0.64, 0.78, 0.64]}
        />
        <mesh
          name="pillar_9"
          castShadow
          receiveShadow
          geometry={nodes.pillar_9.geometry}
          material={materials.Yellow}
          position={[-13.39, 3.35, 8.81]}
          scale={[0.64, 0.78, 0.64]}
        />
        <mesh
          name="Cube001"
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials.Yellow}
          position={[0.71, 3.7, -15.95]}
          rotation={[0, -0.04, 0]}
          scale={[1, 1.19, 1]}
        />
        <mesh
          name="Cube"
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={stoneMaterial}
          position={[0.1, -3.2, 0]}
          rotation={[0, 0.03, 0]}
          scale={0.18}
        />
        <group
          name="room"
          position={[-0.01, -0.76, 0]}
          scale={[15.94, 5.67, 15.94]}
        >
          <mesh
            name="Cylinder001"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001.geometry}
            material={materials.Yellow}
          />
          <mesh
            name="Cylinder001_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_1.geometry}
            material={materials.floor}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/rophnan-scene.glb");
