/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";
import { MeshStandardMaterial } from "three";

export function Rophnan(props) {
  const { nodes } = useGLTF("models/rophnan-scene (2).glb");

  const yellowMaterial = new MeshStandardMaterial({ color: 0x6e5112 }); // Yellow color
  const stoneMaterial = new MeshStandardMaterial({ color: 0x808080 }); // Stone color
  const blackishMaterial = new MeshStandardMaterial({ color: 0x1a1a1a }); // Blackish color for the floor
  const redMaterial = new MeshStandardMaterial({ color: 0x862e01 }); // Red color
  let dynamicMaterial = yellowMaterial;

  if (props.selectedSong === "SHEGIYE _ ሸግዬ .mp3") {
    dynamicMaterial = redMaterial;
  }
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="main_window"
          castShadow
          receiveShadow
          geometry={nodes.main_window.geometry}
          material={dynamicMaterial}
          position={[0.7, 2.6, -16]}
          scale={[0.1, 1.6, 0.1]}
        />
        <mesh
          name="gojo_window"
          castShadow
          receiveShadow
          geometry={nodes.gojo_window.geometry}
          material={dynamicMaterial}
          position={[-13.9, 2.6, -8.1]}
          rotation={[0, 1, 0]}
          scale={[0.1, 1.6, 0.1]}
        />
        <mesh
          name="spear_window"
          castShadow
          receiveShadow
          geometry={nodes.spear_window.geometry}
          material={dynamicMaterial}
          position={[-9.5, 2.6, -13.1]}
          rotation={[0, 0.6, 0]}
        />
        <mesh
          name="shield_window"
          castShadow
          receiveShadow
          geometry={nodes.shield_window.geometry}
          material={dynamicMaterial}
          position={[10.4, 2.6, -12.5]}
          rotation={[0, -0.7, 0]}
        />
        <mesh
          name="axum_window"
          castShadow
          receiveShadow
          geometry={nodes.axum_window.geometry}
          material={dynamicMaterial}
          position={[15, 2.6, -6.4]}
          rotation={[0, -1.2, 0]}
        />
        <mesh
          name="pillar_1"
          castShadow
          receiveShadow
          geometry={nodes.pillar_1.geometry}
          material={dynamicMaterial}
          position={[15.6, 3.5, 3.8]}
          scale={[0.6, 0.7, 0.6]}
        />
        <mesh
          name="pillar_2"
          castShadow
          receiveShadow
          geometry={nodes.pillar_2.geometry}
          material={dynamicMaterial}
          position={[15.7, 3.5, -3.2]}
          scale={[0.6, 0.7, 0.6]}
        />
        <mesh
          name="pillar_3"
          castShadow
          receiveShadow
          geometry={nodes.pillar_3.geometry}
          material={dynamicMaterial}
          position={[12.9, 3.5, -9.6]}
          scale={[0.6, 0.7, 0.6]}
        />
        <mesh
          name="pillar_4"
          castShadow
          receiveShadow
          geometry={nodes.pillar_4.geometry}
          material={dynamicMaterial}
          position={[7.5, 3.5, -14.1]}
          scale={[0.6, 0.7, 0.6]}
        />
        <mesh
          name="pillar_5"
          castShadow
          receiveShadow
          geometry={nodes.pillar_5.geometry}
          material={dynamicMaterial}
          position={[-6.1, 3.5, -14.8]}
          scale={[0.6, 0.7, 0.6]}
        />
        <mesh
          name="pillar_6"
          castShadow
          receiveShadow
          geometry={nodes.pillar_6.geometry}
          material={dynamicMaterial}
          position={[-11.8, 3.5, -10.8]}
          scale={[0.6, 0.7, 0.6]}
        />
        <mesh
          name="pillar_7"
          castShadow
          receiveShadow
          geometry={nodes.pillar_7.geometry}
          material={dynamicMaterial}
          position={[-15.3, 3.5, -4.7]}
          scale={[0.6, 0.7, 0.6]}
        />
        <mesh
          name="pillar_8"
          castShadow
          receiveShadow
          geometry={nodes.pillar_8.geometry}
          material={dynamicMaterial}
          position={[-15.9, 3.5, 2.3]}
          scale={[0.6, 0.7, 0.6]}
        />
        <mesh
          name="pillar_9"
          castShadow
          receiveShadow
          geometry={nodes.pillar_9.geometry}
          material={dynamicMaterial}
          position={[-13.4, 3.5, 8.8]}
          scale={[0.6, 0.7, 0.6]}
        />
        <mesh
          name="Cube"
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={stoneMaterial}
          position={[0.1, -3.2, 0.5]}
          scale={0.18}
        />
        <group name="room" position={[0, 0.1, 0]} scale={[15.9, 4.8, 15.9]}>
          <mesh
            name="Cylinder001"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001.geometry}
            material={dynamicMaterial}
          />
          <mesh
            name="Cylinder001_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_1.geometry}
            material={blackishMaterial}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/rophnan-scene (2).glb");
